resources:
  - 1password.yaml
  - deployment.yaml
  - ingress.yaml
  - onionservice.yaml
  - poddisruptionbudget.yaml
  - service.yaml

configMapGenerator:
  - name: anubis-cfg
    behavior: create
    files:
      - ./cfg/anubis/botPolicies.yaml
