services:
  anubis-nginx:
    image: ko.local/uvensys/anubis:latest
    environment:
      BIND: ":8080"
      DIFFICULTY: "8"
      METRICS_BIND: ":9090"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://nginx"
      #POLICY_FNAME: "/data/cfg/botPolicy.yaml"
      OG_PASSTHROUGH: "false"
      OG_EXPIRY_TIME: "5s"
      COMPANY: "uvensys"  # to select company
      USE_REMOTE_ADDRESS: "true" #for x-real-ip because no proxy is used
    ports:
      - 8080:8080
    #volumes:
      #- "./data/botPolicy.yaml:/data/cfg/botPolicy.yaml:ro"
  nginx: #protected service
    image: nginx
    ports:
      - 80:80
    #volumes:
    #  - "./www:/usr/share/nginx/html"

#DOCKER_REPO=ko.local/uvensys/anubis DOCKER_METADATA_OUTPUT_TAGS=ko.local/uvensys/anubis:latest npm run container