services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.52.0-noble
    init: true
    network_mode: service:workspace
    command:
      - /bin/sh
      - -c
      - npx -y playwright@1.52.0 run-server --port 9001 --host 0.0.0.0

  valkey:
    image: valkey/valkey:8
    pull_policy: always

  # VS Code workspace service
  workspace:
    image: ghcr.io/techarohq/anubis/devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspace/anubis:cached
    environment:
      VALKEY_URL: redis://valkey:6379/0
    #entrypoint: ["/usr/bin/sleep", "infinity"]
    user: vscode
